version: '3.3'

services:
  postgres:
      image: postgres:9.5.10
      restart: always
      environment:
        POSTGRES_USER: 'postgres'
        POSTGRES_PASSWORD: '1234'
        POSTGRES_DB: 'db_name'
      ports:
      - "5432:5432"
      volumes:
      - ./data/postgres/:/var/lib/postgresql/data
